name: 'setup-castor'
description: 'Install castor with a static binary'
author: 'Joel Wurtz'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  version:
    description: 'Castor version to use'
    required: false
    default: 'latest'
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
